import { type AppType } from "next/app";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import "../styles/globals.css";
import { trpc } from "../utils/trpc";

//TODO: Lägg till länk tillbaka till ztek.se

const MyApp: AppType = ({ pageProps, Component }) => {
  return (
    <>
      <Head>
        <title>zFoto</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/zFoto.png" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Header />
        <main className="my-8 flex-grow">
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default trpc.withTRPC(MyApp);
