import type { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import "../styles/globals.css";
import { trpc } from "../utils/trpc";

const MyApp: AppType<{
  session: Session;
}> = ({ pageProps, Component }) => {
  return (
    <SessionProvider session={pageProps.session}>
      <Head>
        <title>zFoto</title>
        <link href="/zFoto.svg" rel="icon" />
        <meta content="Generated by create-t3-app" name="description" />
        <meta content="*" httpEquiv="Access-Control-Allow-Origin" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Header />
        <main className="my-8 flex-grow">
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </SessionProvider>
  );
};

export default trpc.withTRPC(MyApp);
